In [1]:
from sklearn.datasets import make_classification

In [6]:
#define dataset
X, y = make_classification(n_samples = 1000, n_features = 20, n_informative = 15, n_redundant = 5, random_state = 2021)

In [8]:
X

array([[ -0.20893423,   1.36700151,   1.28145226, ...,   0.89236161,
          0.64681566,  -1.38367292],
       [  0.79842987,  -0.83188152,   0.86735658, ...,  -5.68339666,
         -3.30374327,  -1.65227462],
       [  1.40720693,   4.14187512,   2.83432804, ..., -10.87899066,
         -4.56317034,  -2.41004266],
       ...,
       [  0.69775368,  -0.16734138,   3.54745632, ...,  -7.35485077,
         -2.26306054,   1.55321608],
       [  3.15518514,  -0.85820749,   3.48005263, ...,  -2.71738103,
         -1.24117129,   7.00314864],
       [ -2.08342911,   2.20355602,   0.98551698, ...,   7.01586175,
          0.39067048, -12.01131927]])

In [9]:
y

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,

In [22]:
#LogisticsRegression
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, RepeatedKFold
from sklearn.model_selection import cross_val_score

In [23]:
#model
my_cv = RepeatedKFold(n_splits = 10, n_repeats=3, random_state=1)

In [24]:
#create model
model = LogisticRegression()

In [25]:
# fold 1. - hold part 1, remain train --> score --> error 1
# fold 2. - hold part 2, remain train --> score --> error 2
# ....
# fold k. - hold part k, remain train --> score --> error k
# K SCORE --- MEAN, STD
# n_jobs = -1 (chỉ dùng vs máy cá nhân vì nó xài hết core của máy)

scores = cross_val_score(model, X, y, scoring = 'accuracy', cv = my_cv, n_jobs = -1)


In [26]:
scores

array([0.78, 0.79, 0.74, 0.77, 0.79, 0.78, 0.78, 0.79, 0.83, 0.81, 0.8 ,
       0.81, 0.79, 0.83, 0.77, 0.82, 0.7 , 0.81, 0.75, 0.78, 0.78, 0.82,
       0.72, 0.76, 0.81, 0.8 , 0.77, 0.74, 0.86, 0.85])

In [27]:
np.mean(scores)

0.7876666666666666

In [28]:
np.std(scores)

0.03527825896434737

In [29]:
# mean +_std (cross_validation)
# 0.784+_0.043